import asyncio
from logging.config import fileConfig

from sqlalchemy import pool
from sqlalchemy.engine import Connection
from sqlalchemy.ext.asyncio import async_engine_from_config
from sqlalchemy.sql.schema import SchemaItem

from alembic import context
from app.core.config import get_settings
from app.db.base import Base
from app.db.models import *  # noqa: F401,F403 - registers models on Base.metadata

config = context.config
if config.config_file_name is not None:
    fileConfig(config.config_file_name)

# Migrations run as app_owner, which owns the tables and so bypasses RLS.
config.set_main_option("sqlalchemy.url", get_settings().migration_database_url)

target_metadata = Base.metadata

# Objects that exist in the database by migration only, and deliberately have
# no ORM declaration to compare against.
_MIGRATION_ONLY_TABLES = {"rls_probe"}


def include_object(
    object_: SchemaItem,
    name: str | None,
    type_: str,
    reflected: bool,
    compare_to: SchemaItem | None,
) -> bool:
    """Keep autogenerate from proposing to drop hand-written schema.

    Without this hook, `alembic revision --autogenerate` emits `op.drop_index`
    / `op.drop_table` for eight objects that live in migrations but not in
    `Base.metadata`:

    * `rls_probe` - the RLS-policy test fixture table (0002_rls_probe), which
      is intentionally not an ORM model.
    * every `ix_*` index and, most importantly,
      `uq_prompt_versions_one_active` - the partial unique index
      (`WHERE is_active`) that enforces the product's "exactly one active
      prompt version per prompt" guarantee. Alembic cannot express a partial
      index in ORM metadata, so it is created in raw SQL in 0004_prompts and
      would look like an orphan to the comparison.

    One guard here rather than a "do not autogenerate this away" warning in
    each migration file: the next person to run autogenerate is not
    necessarily the next person to read those files.

    Indexes are therefore excluded from comparison wholesale. The cost is that
    a genuinely new ORM-declared index is not autogenerated either and has to
    be written by hand - acceptable next to silently dropping the uniqueness
    guarantee the prompt system depends on.
    """
    if type_ == "index":
        return False
    if type_ == "table" and name in _MIGRATION_ONLY_TABLES:
        return False
    return True


def do_run_migrations(connection: Connection) -> None:
    context.configure(
        connection=connection,
        target_metadata=target_metadata,
        compare_type=True,
        include_object=include_object,
    )
    with context.begin_transaction():
        context.run_migrations()


async def run_async_migrations() -> None:
    connectable = async_engine_from_config(
        config.get_section(config.config_ini_section, {}),
        prefix="sqlalchemy.",
        poolclass=pool.NullPool,
    )
    async with connectable.connect() as connection:
        await connection.run_sync(do_run_migrations)
    await connectable.dispose()


def run_migrations_offline() -> None:
    context.configure(
        url=config.get_main_option("sqlalchemy.url"),
        target_metadata=target_metadata,
        literal_binds=True,
        include_object=include_object,
    )
    with context.begin_transaction():
        context.run_migrations()


if context.is_offline_mode():
    run_migrations_offline()
else:
    asyncio.run(run_async_migrations())
